bool(true)
bool(true)
bool(false)
bool(false)
bool(false)

Warning: input_has_variable() expects parameter 2 to be string, array given in %s on line %d
NULL
bool(true)
bool(true)
bool(false)
bool(false)
bool(false)

Warning: input_has_variable() expects parameter 2 to be string, array given in %s on line %d
NULL
bool(false)

Warning: input_has_variable() expects parameter 1 to be long, string given in %s on line %d
NULL

Warning: input_has_variable() expects parameter 1 to be long, array given in %s on line %d
NULL

Warning: input_has_variable() expects parameter 1 to be long, array given in %s on line %d
NULL

Warning: input_has_variable() expects parameter 1 to be long, string given in %s on line %d
NULL
Done